---
name: "Bug report"
description: "Report a bug on an existing feature of a created integration."
labels: ["bug"]
body:
- type: markdown
  attributes:
    value:  |
      If your integration is NOT created successfully, then you should open a [Config Flow Discovery Issue](https://github.com/NicoIIT/ha-ble-adv/issues/new?template=discovery.yml) instead.

      As a remainder:
      * YOU have a problem
      * YOU are requesting the maintainer to help YOU
      * The maintainer is working for free and has no obligation to help YOU

      The maintainer may be annoyed and reluctant to help you if:
      * the answer to your issue is already in the docs that you obviously did not carefully read, so please read the docs first
      * your issue was already adressed in another Issue (opened or closed), so please check other issues before opening a new one
      * some of the mandatory info is not provided (or not provided in the requested format) and then the issue CANNOT be investigated
      * you do not fill the mandatory info by lazyness with comments such as 'not available' or 'not needed' or 'let me know if you need more info': all requested info ARE available AND needed and MUST be provided directly.

      If the maintainer is annoyed:
      * YOUR issue will be rejected
      * YOU will have no help with YOUR problem

      If the maintainer is REALLY annoyed:
      * YOUR future issues or requests will be ignored
      * YOU will be banned.

- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is. 'It does not work' is not a valid description. Do not hesitate to add screenshots of the errors you are facing."
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to understand and even harder to fix. Please specify the EXACT time (with 'second' precision) at which you performed a specific action so that we can correlate with the time in the debug logs. The description of the action must also be very clear as in the example below, in particular on which device / controller you perform which action."
    value: |
      1. At 15:32:51 I pressed on the "Light On" button of my Physical Remote linked to ble_adv integration 'My Controller name'
      2. At 15:33:10 I changed the light from Cold to Warm using HA UI but the device went from Warm to Cold instead
      3.
      ...
  validations:
    required: true

- type: textarea
  attributes:
    label: "Debug logs"
    description: |
      To enable debug logs please check the [Configuration Guide](https://github.com/NicoIIT/ha-ble-adv/wiki/Configuration-Guide#global-options).
      To know how to access those logs please check Home Assistant doc.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: |
      Drag the integration [diagnostic dump](https://www.home-assistant.io/integrations/diagnostics/) file here.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I checked the [troubleshooting guide](https://github.com/NicoIIT/ha-ble-adv/wiki/Troubleshooting-Guide) and the [configuration guide](https://github.com/NicoIIT/ha-ble-adv/wiki/Configuration-Guide) and it did not solve my issue
        required: true
      - label: I provided ALL mandatory info and in the requested format because I know that in the countrary the maintainer will not help.
        required: true
      - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
        required: true
      - label: This issue is not a duplicate issue of any [previous issues](https://github.com/NicoIIT/ha-ble-adv/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug).
        required: true
