---
name: "Config Flow Discovery Issue"
description: "Report an issue occuring while trying to discover or confirm a configuration (no configuration discovered, the light does not blink, ...)."
labels: ["bug"]
body:
- type: markdown
  attributes:
    value:  |
      If you managed to make the light blink and to create the integration please use a [Bug Report](https://github.com/NicoIIT/ha-ble-adv/issues/new?template=bug.yml) instead.

      > [!CAUTION]
      > As a remainder you are asking for help that the maintainer will happily provide if:
        * you already carefully checked the doc and have not found the answer to your issue
        * your issue contains the requested info needed by the maintainer to be able to investigate it.
      If it is not the case the issue will be **immediately closed** referring to one of the [rejection reasons](https://github.com/NicoIIT/ha-ble-adv/wiki/Why-was-my-issue-rejected%3F).

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I carefully read the [Troubleshooting Guide](https://github.com/NicoIIT/ha-ble-adv/wiki/Troubleshooting-Guide) and it did not help.
        required: true

- type: textarea
  attributes:
    label: Describe your setup
    description: "Describe your setup by completing what follows (Please note some of the values MUST follow the recommended values in the Troubleshooting Guide)."
    value: |
      - Device Brand / Type (if known): XXXXXXX
      - Controller Type you are trying to duplicate: Remote / Phone App / Both / None (Manual or Pairing Flow)
      - Supported ANDROID Phone App recommended by the Device manufacturer: XXXXXXX
      - The Phone App is paired to my Device and controlling it: Yes / No
      - Distance between the controller (Phone or Remote) and the Bluetooth Adapter: XX meters in direct view (no wall)
      - Distance between the controller and the Device: XX meters in direct view (no wall)
      - Distance between the Device and the Bluetooth Adapter: XX meters with a 30cm concrete wall in between

  validations:
    required: true

- type: textarea
  attributes:
    label: Describe your issue
    description: "Describe your issue and all the steps you followed in the troubleshooting guide."
    value: |
      EXAMPLE:

      When I try the recommended 'Duplicate Config' flow using the Phone App as a basis, 4 configurations are detected but none of them is making the light blink.

      I followed the troubleshouting guide until step 3.2a.2, including the bluetooth range check, without success.

  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: |
      Drag here the diagnostic dump you downloaded during the failing configuration flow, or from the place given in the Troubleshooting guide.
  validations:
    required: true
