---
name: "Config Flow Discovery Issue"
description: "Report an issue occuring while trying to discover or confirm a configuration (no configuration discovered, the light does not blink, ...)."
labels: ["bug"]
body:
- type: markdown
  attributes:
    value:  |
      If you managed to make the light blink and to create the integration please use a [Bug Report](https://github.com/NicoIIT/ha-ble-adv/issues/new?template=bug.yml) instead.

      > [!CAUTION]
      > As a remainder you are asking for help that the maintainer will happily provide if:
      > * you already carefully checked the doc and have not found the answer to your issue
      > * your issue contains the requested info needed by the maintainer to be able to investigate it.
      >
      > If it is not the case the issue will be **immediately closed** referring to one of the [rejection reasons](https://github.com/NicoIIT/ha-ble-adv/wiki/Why-was-my-issue-rejected%3F).

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I **_CAREFULLY_** read the [Contribution Guidelines](../CONTRIBUTING.md) of the project and this issue fully complies with them.
        required: true
      - label: I **_CAREFULLY_** checked the [troubleshooting guide](https://github.com/NicoIIT/ha-ble-adv/wiki/Troubleshooting-Guide) and the [configuration guide](https://github.com/NicoIIT/ha-ble-adv/wiki/Configuration-Guide) and it did not solve my issue
        required: true

- type: textarea
  attributes:
    label: Device Brand / Type if known
    description: "If unknown just say it."
  validations:
    required: true

- type: textarea
  attributes:
    label: Supported ANDROID Phone App recommended by the Device manufacturer
    description: "If unknown you should read the [README](../README.md) more carefully..."
  validations:
    required: true

- type: dropdown
  attributes:
    label: "Bluetooth Adapter Type"
    description: "If nothing is selected, the issue will be rejected."
    options:
      - "--- Select a type ---"
      - "Bluetooth Adapter of the HA Server"
      - "Ble Adv Proxy"
  validations:
    required: true

- type: dropdown
  attributes:
    label: "Controller Type you try to duplicate"
    description: "If nothing is selected, the issue will be rejected."
    options:
      - "--- Select a type ---"
      - "Physical Remote"
      - "Supported Phone Application"
      - "Unsupported Phone Application"
  validations:
    required: true


- type: checkboxes
  attributes:
    label: Paired Controller
    options:
      - label: The Controller I am trying to duplicate is paired to my Device and controlling it


- type: input
  attributes:
    label: Distance in meters between the controller (Phone or Remote) and the Bluetooth Adapter
  validations:
    required: true
    regex: "^[0-9]+$"

- type: input
  attributes:
    label: Distance in meters between the controller and the Device
  validations:
    required: true
    regex: "^[0-9]+$"

- type: input
  attributes:
    label: Distance in meters between the Device and the Bluetooth Adapter
  validations:
    required: true
    regex: "^[0-9]+$"

- type: checkboxes
  attributes:
    label: Wall Checks
    options:
      - label: There is NO obstacle such as a wall in between the Controller and the Bluetooth Adapter
      - label: There is NO obstacle such as a wall in bewteen the Controller and the Device
      - label: There is NO obstacle such as a wall in between the Device and the Bluetooth Adapter


- type: textarea
  attributes:
    label: Describe your issue
    description: "Describe your issue and all the steps you followed in the troubleshooting guide. If ONE step is missing that _could_ have explained your problem, the issue will be rejected."
    placeholder: |
      When I try the recommended 'Duplicate Config' flow using the Phone App as a basis, 48 configurations are detected but none of them is making the light blink.

      I followed the troubleshouting guide step (01.19.19 - Kick my A**), and it worked OK.

  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: |
      Drag here the diagnostic dump you downloaded during the failing configuration flow, or from the place given in the Troubleshooting guide.
  validations:
    required: true
