---
name: "Feature request"
description: "Request the addition of a new feature or the improvment of an existing feature of this Project"
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Before you open a new feature request, search through the existing feature requests to see if others have had the same idea.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template to the best of my ability.
        required: true
      - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
        required: true
      - label: This issue is not a duplicate feature request of [previous feature requests](https://github.com/NicoIIT/ha-ble-adv/issues?q=is%3Aissue%20state%3Aopen%20label%3Aenhancement).
        required: true
      - label: I am not requesting for the support of a new device brand, as this integration is supporting Android Phone App protocols and not device brands.
        required: true
      - label: I am not opening a "feature request" just because I do not want to fill templates for "Bug Report" (in particular provide steps to reproduce and debug logs).
        required: true

- type: textarea
  attributes:
    label: "Describe what you'd like as a new feature"
    description: "A clear and concise description of what you want to happen."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe alternatives you've considered"
    description: "A clear and concise description of any alternative solutions or features you've considered."
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional context"
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: false
