---
name: "Support New Android Application"
description: "Request for the support of a new ANDROID Phone Application that is using BLE ADV as a mechanism to control a Device."
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Before you open a new app request, search through the existing app requests to see if others have had the same request already.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have checked the [README](https://github.com/NicoIIT/ha-ble-adv?tab=readme-ov-file#home-assistant-ble-adv-ceiling-fan--lamps) and the Phone App is not already supported.
        required: true
      - label: This issue is not a duplicate app request of [previous app requests](https://github.com/NicoIIT/ha-ble-adv/issues?q=is%3Aissue%20state%3Aopen%20label%3Aenhancement).
        required: true
      - label: I am not requesting for the support of a new device brand, as this integration is supporting Android Phone App protocols and not device brands.
        required: true
      - label: I checked the Phone App is effectively using BLE ADV commands to control my Device using the [Listening Tool](https://github.com/NicoIIT/ha-ble-adv/wiki/How-to-know-if-my-Physical-Remote-is-using-BLE-Advertising-to-control-my-device#the-included-listening-tool).
        required: true

- type: textarea
  attributes:
    label: "Android Phone app info"
    description: "All the info you have to allow the developper to find it and install it. (EXACT name on the Android App Store, download link, ...)"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Example BLE ADV messages"
    description: "Provide here the BLE ADV messages you captured using the [Listening Tool](https://github.com/NicoIIT/ha-ble-adv/wiki/How-to-know-if-my-Physical-Remote-is-using-BLE-Advertising-to-control-my-device#the-included-listening-tool) while pressing 5 times on the same (preferably Pair) Button of the phone App"
  validations:
    required: true
