---
name: "Support New Physical Remote"
description: "Request support for new Physical Remote not recognized yet."
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Before you open a new "Support New Physical Remote" request, search through the existing feature requests to see if others have requested it already. If your remote is recognized but only partially works please open a Bug Report.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template COMPLETELY. In particular if either of the mandatory info is not given then your request is useless and will be Closed.
        required: true
      - label: This only contains 1 "Support New Physical Remote" request (if you have multiple requests, open one request for each).
        required: true
      - label: This issue is not a duplicate "Support New Physical Remote" request of [previous requests](https://github.com/NicoIIT/ha-ble-adv/issues?q=is%3Aissue%20state%3Aopen%20label%3Aenhancement).
        required: true

- type: textarea
  attributes:
    label: "Describe ALL buttons"
    description: "Describe all buttons, what happens on the device when you press them once (and a second time if the result differs), and at what time exactly ('second' precision) you pressed them so that we can correlate this info with the logs."
    value: |
      1. Button "Fan ON/OFF":
        * At 15:32:51 I pressed the button and the Fan started
        * At 15:32:55 I pressed again the button and the Fan stopped
      2. Button "Main Light Brightness+"
        * At 15:33:11 I pressed the button and the light brightness increased by 15 % (6 press to go from minimum to maximum brightness)
      3. Button ...
      ...
  validations:
    required: true

- type: textarea
  attributes:
    label: "Debug logs"
    description: |
      To enable debug logs add this to your [configuration.yaml](https://www.home-assistant.io/docs/configuration/), and restart your HA:
      ```
      ble_adv:

      logger:
        default: info
        logs:
          custom_components.ble_adv: debug
      ```
      More details in [logger](https://www.home-assistant.io/integrations/logger/) component.

      This **needs** to include all logs generated when you pressed buttons, in particular the `BLE ADV received` ones:
      ```
      2025-04-30 08:43:28.981 DEBUG (MainThread) [custom_components.ble_adv.coordinator] [hci/48:45:20:37:67:BF] BLE ADV received - Type: 0xFF, raw: FF.FF.C4.8B.78.8E.07.E2
      ```

      If not provided, the issue will be Closed immediately.
    render: text
  validations:
    required: true
