# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.ble_adv: debug

ble_adv:
  ignored_duration: 10000
  ignored_macs:
    - 64:F0:AD:38:DC:E2
    - C4:8B:78:8E:07:E2
    - 4C:A9:19:26:87:26
    - 49:F0:C3:DE:C5:1C
    - 18:DE:50:8C:BA:83
    - 24:DC:C3:C2:15:DE # esp-leds-proxy
    - 48:45:20:37:67:BF # hci/48:45:20:37:67:BF
  # ignored_cids:
  #   - 0xfef3 # Google

  # ignored_adapters:
  #   - hci/48

recorder:
  exclude:
    event_types:
      - call_service